version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.2.3
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__FERNET_KEY=
      - AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION=True
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - airflow-dags-volume:/opt/airflow/dags
      - airflow-logs-volume:/opt/airflow/logs

  airflow-scheduler:
    image: apache/airflow:2.2.3
    environment:
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
    depends_on:
      - airflow-webserver
    volumes:
      - airflow-dags-volume:/opt/airflow/dags
      - airflow-logs-volume:/opt/airflow/logs
    command: scheduler

volumes:
  postgres-db-volume:
  airflow-dags-volume:
  airflow-logs-volume:
